<a href="https://colab.research.google.com/github/erebicraft/elisha3vi/blob/main/1_introduction_to__a_i_and__machine__learning__live__lecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.0 👏 Welcome  

Dear Dareans, welcome to the exciting world of **AI and Machine Learning**! We are thrilled to have you embark on this transformative journey with us. As your Sensei, we will guide you through the principles, techniques, and tools that form the bedrock of AI and ML. Whether you're new to the field or looking to deepen your understanding, this course is designed to help you build a strong foundation and develop practical skills that will prepare you for real-world applications.

This program is a **comprehensive learning experience** divided into modules tailored to progressively enhance your knowledge. Over the coming weeks, you will explore cutting-edge concepts, solve real-world challenges, and build intelligent systems. The course is organized into the following modules:  

1. **Introduction to Machine Learning** : The awakening of Intelligence
2. **ML Techniques**: Introducing Machine learning algorithms
3. **Advanced ML Techniques**: Delve deeper into advanced algorithms.
2. **Natural Language Processing**: Teach machines to understand human language.
3. **Computer Vision**: Enable machines to see and interpret the world.
4. **Big Data and Cloud Computing**: Scale your knowledge to handle massive datasets.
5. **Optimization and Deployment**: Refine and implement your solutions.

Get ready for an interactive, engaging, and innovative journey into the heart of AI!  

---

# 1.1 🛠️ Prerequisites  

Before diving into this **AI and Machine Learning** course, it is essential to have a solid foundation in the following areas:  

- 1. **Python Programming**: The universal language of AI, Python is our primary tool. Knowledge of libraries like NumPy, Pandas, and Matplotlib will be your sword and shield.

- 2. **Mathematical Foundations**: Just as a castle is built on a strong foundation, ML relies on linear algebra, calculus, and statistics to stand tall.

### 1.1.1  Why These Prerequisites Matter:  
These prerequisites ensure that you:  
- Have the programming skills to implement machine learning algorithms effectively.  
- Are familiar with working on data-driven projects and can handle datasets confidently.  
- Can focus on mastering AI and ML concepts without struggling with foundational skills.  

If you need to revisit these topics, we recommend reviewing the materials from our **Python Programming** and **Data Science** courses before starting this track.

Lets begin!!

---

### 1.2.5 🎥 Recommended Videos

Here are some YouTube videos to help you better understand the different The Basics of machine learning:  

1. **[Basics of Machine Learning](https://www.youtube.com/watch?v=ETfWKZIu-sk)**   

2. **[Supervised and Unsupervised Explained](https://www.youtube.com/watch?v=W01tIRP_Rqs)**


NOTE: I recommend you use **"Brave Browser"** to watch any recommended Youtube Videos, to bypass youtube adverts for your convenience. You can download the free Brave Browser from here 👉 [Brave browser](https://www.brave.com/)


Also

**Important Note**: Due to the intense GPU requirements for training neural networks, we recommend running some examples and mini-projects on Google Colab. This platform provides free access to GPU acceleration, making it an ideal environment for hands-on learning.
To get started, we've included a brief training on Google Colab below.

👉 [Get started with Google Colaboratory](https://www.youtube.com/watch?v=inN8seMm7UI)


# 1.2 🖥️Introduction to Machine Learning  :  The Awakening of Intelligence

**Start your journey with the building blocks of Machine Learning!**  

### 1.2.1 Learning Outcomes  
Upon completing this module, you will:  

- Understand the differences between supervised and unsupervised learning.
- Appreciate the mathematical foundations necessary for ML e.g linear algebra and Calculus
- Learn data preprocessing techniques, including handling missing data, encoding categorical variables, and feature scaling.  
- Gain hands-on experience with fundamental regression and classification algorithms, including:

 - **K-Nearest Neighbors (KNN)**: Picture a friendly neighbor helping you make decisions based on their experience.
 - **Decision Trees**: A tree that grows based on questions and answers, guiding us to a decision.
 - **Naïve Bayes**: A probabilistic approach, making informed guesses based on past data.
 - **Linear and Logistic Regression**: The pioneers of ML, using equations to predict continuous and categorical outcomes.
 - **Support Vector Machines (SVM)**: A vigilant guard, creating boundaries to distinguish between categories.
 - Complete a project using multiple linear regression to analyze the relationship between sales and various marketing  promotion strategies

This module lays the groundwork for your journey into Machine Learning, equipping you with the core skills required for success.


### 1.2.2 🤖 What Is Machine Learning?  

Machine learning is the **science (and art)** of programming computers so they can learn from data.  

#### Definitions:  

1. **General Definition:**  
   *"[Machine learning is the] field of study that gives computers the ability to learn without being explicitly programmed."*  
   — *Arthur Samuel, 1959*  

2. **Engineering-Oriented Definition:**  
   *"A computer program is said to learn from experience E with respect to some task T and some performance measure P, if its performance on T, as measured by P, improves with experience E."*  
   — *Tom Mitchell, 1997*  




A spam filter is a classic example of a machine learning system. Here's how it works:  

- The system is trained using **examples of spam emails** (flagged by users) and **examples of regular emails** (non-spam, also known as “ham”).  
- The examples used to train the system are called the **training set**, and each individual example is referred to as a **training instance** (or sample).  
- The core of the machine learning system—the component that learns and makes predictions—is called the **model**. Examples of models include **neural networks** and **random forests**.  

#### Breaking It Down  
In this scenario:  
- **Task (T):** Flagging spam emails.  
- **Experience (E):** Learning from the training data (examples of spam and ham emails).  
- **Performance Measure (P):** The ratio of correctly classified emails. This performance metric is known as **accuracy** and is commonly used in classification tasks.  

Machine learning allows the spam filter to improve its performance on the task as it gains more experience from the training data.  


### 1.2.3 🌟 Some Applications of Machine Learning  

Machine learning can tackle an incredible variety of tasks across different domains. Here are some examples:  

#### 1. Analyzing Images on a Production Line
* **Task:** Automatically classify products.
* **Approach:** Image classification, typically performed using convolutional neural networks (CNNs) or transformers.


#### 2. Detecting Tumors in Brain Scans
* **Task:** Semantic image segmentation (classifying each pixel in the image to determine the exact location and shape of tumors).
* **Approach:** Typically achieved using CNNs or transformers.


#### 3. Classifying News Articles
* **Task:** Text classification in natural language processing (NLP).
* **Approach:** Recurrent neural networks (RNNs), CNNs, or transformers (which provide better results).


#### 4. Flagging Offensive Comments on Discussion Forums
* **Task:** Text classification in NLP.
* **Approach:** Similar tools as for news article classification.


#### 5. Summarizing Long Documents
* **Task:** Text summarization, a branch of NLP.
* **Approach:** Uses transformers and other NLP tools.


Others include forecasting company revenue, making an app react to voice commands, detecting credit card fraud, segmenting clients based on purchases, visualizing high-dimensional data, recommending products to clients, building an intelligent game bot, and more.


### 1.2.4 🏷️ Types of Machine Learning Systems

Machine learning systems come in different types, depending on how they work and learn. Let’s break it down in a simple and engaging way:

---

#### 1. **How They Learn During Training**

- **Supervised Learning**
  - Imagine having a teacher who gives you both questions and answers to learn from. That’s supervised learning! The system is trained using labeled data (data with known answers).
  - **Example**: Predicting house prices based on historical data where the prices are already known.

- **Unsupervised Learning**
  - Here, there’s no teacher, just patterns to discover. The system learns from unlabeled data, figuring things out on its own.
  - **Example**: Grouping similar customers based on their shopping habits using clustering.

- **Semi-Supervised Learning**
  - This is like having a mix of a few questions with answers and many questions without them. The system learns from a combination of labeled and unlabeled data.
  - **Example**: Training a model with some labeled photos and many unlabeled ones.

- **Self-Supervised Learning**
  - Think of it as a puzzle: the system uses parts of the data to figure out other parts. It generates labels from the data itself.
  - **Example**: Predicting the next word in a sentence by learning from previous words.

- **Reinforcement Learning**
  - Imagine playing a video game where you learn by trial and error. You get rewards for good moves and penalties for bad ones. That’s reinforcement learning!
  - **Example**: Teaching a bot to play chess and improve by learning the best moves over time.

---

#### 2. **How They Handle Data: Online vs. Batch Learning**

- **Online Learning**
  - The system learns bit by bit, updating itself as new data comes in, like learning on the go.
  - **Example**: Predicting stock prices in real-time as new data keeps flowing in.

- **Batch Learning**
  - Here, the system learns all at once from a complete dataset before it’s ready to be used. It’s like studying an entire textbook before taking the test.
  - **Example**: Training a model on a fixed dataset and then deploying it for use.

---

#### 3. **How They Use Data: Instance-Based vs. Model-Based Learning**

- **Instance-Based Learning**
  - Think of it as keeping a memory bank of past experiences and comparing new situations to those memories.
  - **Example**: k-Nearest Neighbors (k-NN), which classifies data by looking at its closest neighbors.

- **Model-Based Learning**
  - Here, the system builds a general model based on patterns it finds in the data, like coming up with rules after observing examples.
  - **Example**: Linear regression, which predicts outcomes by finding relationships in the data.

---

By understanding these types, you can see how machines learn and make decisions in different ways. It’s like giving them different strategies to tackle the world’s problems!






### 1.2.6  🧮 Mathematical Foundations for Machine Learning: Linear Algebra

Linear algebra is the foundation of many machine learning algorithms. Let’s break it down into simple terms to understand its key concepts and importance.

---

#### What Is Linear Algebra?
Linear algebra is a branch of mathematics focused on vectors, matrices, and the operations you can perform on them. In machine learning, it helps us represent and manipulate data efficiently.

---

#### Key Concepts

1. **Vectors**
   - Think of a vector as an organized list of numbers. It’s often used to represent a single data point.
   - **Example**: A person’s features like height, weight, and age can be a vector:
     
     `[Height, Weight, Age] = [5.9, 72, 30]`

2. **Matrices**
   - A matrix is like a table with rows and columns, where each row represents a data point and each column represents a feature.
   - **Example**:

     | Height | Weight | Age |
     |--------|--------|-----|
     | 5.9    | 72     | 30  |
     | 5.6    | 68     | 28  |
     | 6.0    | 80     | 32  |

3. **Vector and Matrix Operations**
   - **Addition/Subtraction**: Combine or compare vectors and matrices.
   - **Dot Product**: Measure the similarity between two vectors (used in recommendations or clustering).
   - **Matrix Multiplication**: Transform or project data by combining matrices.

4. **Similarity Between Vectors**
   - Vectors can show how related data points are.
   - **Cosine Similarity**: Compares the direction of two vectors, useful for identifying similar products or users in recommendation systems.

---

#### Why Is Linear Algebra Important in Machine Learning?
Linear algebra helps us:
- **Organize data**: Represent datasets in ways that are easy to work with.
- **Transform data**: Rotate, scale, or project data into different dimensions for better insights.
- **Train models**: Perform calculations like gradient descent to optimize machine learning models.

In essence, linear algebra gives us the tools to **process and analyze data** efficiently, making machine learning possible.

---

#### Learn More
Dive deeper into linear algebra with these resources:
- [Math Linear Algebra Notebook](resources/math_linear_algebra.ipynb)
- [Khan Academy: Linear Algebra Lessons](https://www.khanacademy.org/math/linear-algebra)
- [Wikipedia: Linear Algebra](https://en.wikipedia.org/wiki/Linear_algebra)
- [Free Text on Linear Algebra](https://linear.axler.net/)

Linear algebra might seem complex at first, but with practice, it becomes an essential tool in your machine learning journey!



### 1.2.7 🧮 Mathematical Foundations for Machine Learning: Calculus

Calculus plays a crucial role in machine learning, helping models learn and optimize. It’s all about understanding how changes in inputs affect outputs and ensuring models perform at their best.

---

#### What Is Calculus?
Calculus is a branch of mathematics focused on two key ideas:
- **Rates of Change (Differentiation):** How things change.
- **Accumulation (Integration):** Summing up small parts to understand the whole.

In machine learning, we mostly use differentiation.

---

#### Key Concepts

1. **Derivatives (Differentiation):**
   - Derivatives measure how a function changes as its input changes.
   - In machine learning, they help calculate **gradients**, which are crucial for optimizing models.
   - **Example**: Gradients show how to adjust parameters to reduce prediction errors.

2. **Gradient Descent:**
   - Gradient descent is an algorithm that uses derivatives to find the minimum value of a function (like a loss function).
   - It adjusts model parameters step-by-step in the direction that reduces error the fastest.

3. **Partial Derivatives:**
   - When dealing with multiple variables (like weights in a neural network), partial derivatives show how a function changes with respect to each variable.
   - They are essential for training models with many parameters.

4. **Chain Rule:**
   - The chain rule helps compute derivatives of composite functions.
   - It’s a core component of **backpropagation**, the algorithm used to train neural networks.

5. **Integration:**
   - While less common, integration is useful for calculating areas under curves and probabilistic models, like those in Bayesian inference.

---

#### Why Is Calculus Important in Machine Learning?
- **Optimization:** Calculus minimizes errors by fine-tuning model parameters.
- **Training Models:** Neural network training, through backpropagation, relies heavily on differentiation.
- **Understanding Change:** Models like regression and neural networks depend on how small changes in inputs impact outputs.

In essence, calculus powers the optimization and learning processes that make machine learning models accurate and effective.

---

#### Learn More
To dive deeper into calculus for machine learning, check out these resources:
- [Math - Differential Calculus Notebook](resources/math_differential_calculus.ipynb)

Calculus might seem daunting, but with practice, it becomes a powerful tool in your machine learning toolkit!



# 1.3 🔧 Data Preprocessing: Preparing Data for Machine Learning  

Data preprocessing is a critical step in machine learning. Raw data is rarely perfect—it often contains missing values, inconsistent formats, or variables that need to be scaled or encoded. Preprocessing ensures that your data is clean, consistent, and ready for analysis.

---

### Key Steps in Data Preprocessing  

1. **Handling Missing Data:**  
   - Missing values can disrupt machine learning models. Here’s how to handle them:  
     - **Remove Rows/Columns:** If too many values are missing, it may be better to drop the affected rows or columns.  
     - **Imputation:** Replace missing values with an estimate, such as:  
       - The mean, median, or mode of the column.  
       - A placeholder value (e.g., 0 or “unknown”).  
       - Predictions from other data using advanced techniques.  

   - **Example:**  
     | Name    | Age | Salary  |  
     |---------|-----|---------|  
     | Alice   | 25  | 50000   |  
     | Bob     | NaN | 48000   |  
     | Charlie | 30  | NaN     |  
     → Replace NaN with the mean value of the column.  

2. **Encoding Categorical Variables:**  
   - Machine learning models work with numbers, so we need to convert categorical (non-numerical) data into a numerical format:  
     - **Label Encoding:** Assign a unique number to each category.  
       - Example: `["Red", "Blue", "Green"] → [0, 1, 2]`  
     - **One-Hot Encoding:** Create separate binary columns for each category.  
       - Example:  
         | Color  | Red | Blue | Green |  
         |--------|-----|------|-------|  
         | Red    | 1   | 0    | 0     |  
         | Blue   | 0   | 1    | 0     |  
         | Green  | 0   | 0    | 1     |  

3. **Feature Scaling:**  
   - Features (variables) can have vastly different ranges, which can negatively affect models (e.g., distance-based models like KNN).  
   - Scaling ensures that all features contribute equally to the model. Common methods:  
     - **Min-Max Scaling (Normalization):** Rescales values to a range (e.g., 0 to 1).  
       - Formula: `(x - min) / (max - min)`  
     - **Standardization (Z-Score Scaling):** Centers data around 0 with a standard deviation of 1.  
       - Formula: `(x - mean) / std`  

---

### Why Is Data Preprocessing Important?  
- Ensures models can learn effectively from the data.  
- Reduces bias caused by missing or inconsistent data.  
- Improves accuracy and performance of machine learning models.  

Without proper preprocessing, even the best algorithms may fail to deliver meaningful results.  


## 1.3.1 Example :  Performing Data Preprocessing

#### Step 1: Importing the libraries
**Why?**  
To work with data, we need tools. Think of libraries as toolkits for different jobs:
- **NumPy** helps us do calculations with numbers.
- **Pandas** helps organize and clean data.
- **Matplotlib** (not used here) is for creating graphs to visualize data.  

**How?**  
We load these libraries so we can use their tools in our code.  


In [85]:
# Step 1: Importing the necessary libraries
# numpy: for numerical operations
# matplotlib: for data visualization (not used in this example, but commonly included)
# pandas: for handling and analyzing datasets

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#### Step 3: Importing the dataset
**Why?**  
We need data to teach our machine learning model. The dataset is like a spreadsheet, where:
- **Rows** represent different examples (e.g., people, houses, etc.).
- **Columns** represent features (e.g., height, weight, price).  

**How?**  
We load the dataset into our program and split it into two parts:
- **Features (X):** The information we use to make predictions.
- **Target (y):** The thing we want to predict.  

---

In [86]:
# Import Data Files from Google Drive


import requests
import pandas as pd
from io import StringIO
def read_gd(sharingurl):
    file_id = sharingurl.split('/')[-2]
    download_url='https://drive.google.com/uc?export=download&id=' + file_id
    url = requests.get(download_url).text
    csv_raw = StringIO(url)
    return csv_raw

url = "https://drive.google.com/file/d/1NfbiEKdOxWJ-TR9XZLt6-IXECdSPWUD-/view?usp=drive_link"
gdd = read_gd(url)

df = pd.read_csv(gdd)

dataset = df

dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [87]:
# Step 2: Importing the dataset locally
# Load data from a CSV file and separate it into features (X) and target (y).

# dataset = pd.read_csv('sample_data/Data.csv')
X = dataset.iloc[:, :-1].values  # Select all rows and all columns except the last one
y = dataset.iloc[:, -1].values  # Select all rows from the last column

In [88]:
# Print the feature matrix and target vector to verify the data

print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [89]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


#### Step 3: Taking care of missing data
**Why?**  
Sometimes data is incomplete (e.g., a person forgot to write their age). Missing data can confuse the model.  

**How?**  
We fill in the blanks with reasonable values. Here, we use the **mean** (average) of the other values in the same column. This way, we don’t lose useful information.  

---

In [90]:
# Step 3: Handling missing data
# Replace missing values in specific columns with the mean of those columns


from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')  # Define the imputer
imputer.fit(X[:, 1:3]) # Fit the imputer on columns with missing values
X[:, 1:3] = imputer.transform(X[:, 1:3])  # Apply the transformation

In [91]:
# Print the updated feature matrix
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


#### Step 4:  Encoding categorical data
**Why?**  
Computers don’t understand words like "red" or "cat." They need numbers.  
- For example, "Red, Green, Blue" could become [1, 2, 3].  
Some data might need to be split into multiple columns to avoid confusion (e.g., One-Hot Encoding).  

**How?**  
We convert categories into numbers for:
- **Features:** By creating separate columns for each category (e.g., "Red," "Green," "Blue" become three columns).
- **Target (y):** By assigning numbers to each category (e.g., "Yes" becomes 1, "No" becomes 0).  

---

##### Encoding the Independent Variable

In [92]:
# Step 4: Encoding categorical data
# Convert categorical data into numeric representations for compatibility with ML algorithms

# Encoding the Independent Variable (categorical feature in the first column)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))  # Apply one-hot encoding and convert to numpy array

In [93]:
# Print the updated feature matrix after encoding
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


##### Encoding the Dependent Variable

In [94]:
# Encoding the Dependent Variable (target variable)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y) # Convert categories to numeric labels

In [95]:
# Print the updated target vector
print(y)

[0 1 0 0 1 1 0 1 0 1]


#### Step 5: Splitting the dataset into the Training set and Test set
**Why?**  
We need to test how well our model can predict things it hasn’t seen before. So, we divide the dataset into:
- **Training Set:** Data the model learns from.
- **Test Set:** Data we use to check how well the model has learned.  

**How?**  
We split the data into two parts, often keeping 80% for training and 20% for testing.  

---

In [96]:
# Step 5: Splitting the dataset into the Training set and Test set
# Separate the data into training and test sets for model evaluation

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [97]:
# Print the split datasets
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [98]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [99]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [100]:
print(y_test)

[0 1]


#### Step 6: Feature Scaling
**Why?**  
Some features (e.g., age vs. salary) have very different ranges. This can make the model favor one feature over another. For example, if one column has values like 100,000 and another has values like 5, the model might think the bigger numbers are more important.  

**How?**  
We scale all features to the same range so they’re treated equally. This ensures the model focuses on relationships, not just the size of the numbers.  

---

In [101]:
# Step 6: Feature Scaling
# Standardize features by removing the mean and scaling to unit variance


from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 4:] = sc.fit_transform(X_train[:, 4:]) # Fit and transform the training data (only numerical columns)
X_test[:, 4:] = sc.transform(X_test[:, 4:])  # Transform the test data using the same scaler

In [102]:
# Print the scaled datasets
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 -1.0781259408412422]
 [0.0 1.0 0.0 40.0 -0.0701316764163537]
 [1.0 0.0 0.0 44.0 0.6335624327104549]
 [0.0 0.0 1.0 38.0 -0.3078661727429786]
 [0.0 0.0 1.0 27.0 -1.4204636155515817]
 [1.0 0.0 0.0 48.0 1.2326533634535488]
 [0.0 1.0 0.0 50.0 1.5749910381638883]
 [1.0 0.0 0.0 35.0 -0.5646194287757332]]


In [103]:
print(X_test)

[[0.0 1.0 0.0 30.0 -0.9069571034860726]
 [1.0 0.0 0.0 37.0 0.20564033932253056]]


# 1.4 Machine Learning Algorithms

There are a couple of Machine Learning Algorithms broadly classified into the following headings:

### 1. Regression Algorithms
- **Simple Linear Regression**  
- **Multiple Linear Regression**  
- **Polynomial Regression**  
- **Support Vector Regression (SVR)**  
- **Random Forest Regression**  

### 2. Classification Algorithms
- **Logistic Regression**  
- **K-Nearest Neighbours (kNN)**  
- **Support Vector Machines (SVM)**  
- **Kernel SVM**  
- **Naive Bayes**  
- **Decision Tree Classification**  
- **Random Forest Classification**  

### 3. Clustering Algorithms
- **K-Means Clustering**  
- **Hierarchical Clustering**  


We will look at some of these in the coming lessons

# **Conclusion**

Artificial Intelligence and Machine Learning have transformed how we approach problem-solving, enabling systems to learn from data and make predictions or decisions. In this lecture, we explored the core principles and mathematical foundations underpinning these technologies, along with the data preprocessing steps that form the bedrock of every machine learning project. Remember, the success of any AI system begins with well-prepared data and a strong understanding of the concepts driving it. As you move forward, focus on honing these skills and applying them to real-world challenges. The potential is limitless—what you create with it is up to you!